# -*- coding: utf-8 -*-
"""base64.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFrubxML5q2ZtAywqH_E_rnC5cF1u6ou
"""

import base64

def encode_text(text):
    encoded = base64.b64encode(text.encode('utf-8'))
    return encoded.decode('utf-8')

def decode_text(encoded_text):
    try:
        decoded = base64.b64decode(encoded_text).decode('utf-8')
        return decoded
    except Exception as e:
        return f"Error decoding: {e}"

def main():
    print("=== Base64 Encoder/Decoder ===")
    print("Choose an option:")
    print("1. Encode text")
    print("2. Decode Base64 text")

    choice = input("Enter choice (1 or 2): ").strip()

    if choice == '1':
        text = input("Enter text to encode: ").strip()
        if not text:
            print("Error: Empty input!")
            return
        result = encode_text(text)
        print(f"\n Encoded Base64: {result}")

    elif choice == '2':
        encoded_text = input("Enter Base64 text to decode: ").strip()
        if not encoded_text:
            print("Error: Empty input!")
            return
        result = decode_text(encoded_text)
        print(f"\n Decoded text: {result}")
    else:
        print("Invalid choice. Please enter 1 or 2.")

if __name__ == "__main__":
    main()