# -*- coding: utf-8 -*-
"""caeser_cipher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13rkfboqGzLi0Z9UE5Wt8YSlXAnI6Ud7v
"""

def encrypt(text, shift):
    result = ""
    for char in text:
        if char.isupper():
            result += chr((ord(char) - 65 + shift) % 26 + 65)
        elif char.islower():
            result += chr((ord(char) - 97 + shift) % 26 + 97)
        else:
            result += char
    return result

def decrypt(cipher_text, shift):
    return encrypt(cipher_text, -shift)

def main():
    print("Caesar Cipher Encryption Tool")

    text = input("Enter the text to encrypt: ")
    try:
        shift = int(input("Enter the shift value (integer): "))
    except ValueError:
        print("Invalid shift! Please enter an integer.")
        return

    encrypted = encrypt(text, shift)
    decrypted = decrypt(encrypted, shift)

    print("\n Encrypted Text:", encrypted)
    print("Decrypted Text:", decrypted)

if __name__ == "__main__":
    main()