# -*- coding: utf-8 -*-
"""password_strength_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfNLjOTlyr4txfEb-BExg1y1ZJFeoKdp
"""

import re

def check_strength(password):
    suggestions = []
    strength_score = 0

    if len(password) >= 12:
        strength_score += 2
    elif len(password) >= 8:
        strength_score += 1
    else:
        suggestions.append("Increase the length to at least 12 characters.")

    if re.search(r"[a-z]", password):
        strength_score += 1
    else:
        suggestions.append("Add lowercase letters.")

    if re.search(r"[A-Z]", password):
        strength_score += 1
    else:
        suggestions.append("Add uppercase letters.")

    if re.search(r"\d", password):
        strength_score += 1
    else:
        suggestions.append("Include numbers.")

    if re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
        strength_score += 1
    else:
        suggestions.append("Add special characters (e.g., !, @, #).")

    if strength_score >= 6:
        strength = "Strong"
    elif 4 <= strength_score < 6:
        strength = "Moderate"
    else:
        strength = "Weak"

    return strength, suggestions


def main():
    print(" Password Strength Checker \n")
    password = input("Enter a password to evaluate: ")
    strength, suggestions = check_strength(password)

    print(f"\nPassword Strength: {strength}")
    if suggestions:
        print("\nSuggestions to improve:")
        for tip in suggestions:
            print(f"- {tip}")
    else:
        print("\nGreat job! Your password is strong.")

if __name__ == "__main__":
    main()