# -*- coding: utf-8 -*-
"""secure_password_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOXLu25LHvbHZJ5NbbboPuNKSkODwd45
"""

import random
import string

def generate_password(length, use_upper=True, use_lower=True, use_digits=True, use_special=True):
    characters = ''

    if use_upper:
        characters += string.ascii_uppercase
    if use_lower:
        characters += string.ascii_lowercase
    if use_digits:
        characters += string.digits
    if use_special:
        characters += string.punctuation

    if not characters:
        raise ValueError("At least one character type must be selected!")

    password = ''.join(random.choice(characters) for _ in range(length))
    return password

print(" Secure Password Generator ")

try:
    length = int(input("Enter password length: "))
    use_upper = input("Include UPPERCASE letters? (y/n): ").lower() == 'y'
    use_lower = input("Include lowercase letters? (y/n): ").lower() == 'y'
    use_digits = input("Include digits? (y/n): ").lower() == 'y'
    use_special = input("Include special characters? (y/n): ").lower() == 'y'

    password = generate_password(length, use_upper, use_lower, use_digits, use_special)
    print("\n Generated Password:", password)

except ValueError as e:
    print(" Error:", e)