# -*- coding: utf-8 -*-
"""simple_network_port_scanner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SOVO6nsU_5oEKzdwUq5TiqZGZ4Wgkvti
"""

import socket

def scan_ports(ip, start_port=1, end_port=1024):
    print(f"\nScanning {ip} for open ports...\n")
    open_ports = []
    for port in range(start_port, end_port + 1):
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        socket.setdefaulttimeout(0.5)
        result = sock.connect_ex((ip, port))
        if result == 0:
            try:
                service = socket.getservbyport(port)
            except:
                service = "Unknown Service"
            open_ports.append((port, service))
        sock.close()

    if open_ports:
        print(" Open Ports Found:\n")
        for port, service in open_ports:
            print(f"Port {port}: {service}")
    else:
        print(" No open ports found.")

target_ip = input("Enter target IP address: ")
scan_ports(target_ip)